### ISSUE TITLE
safe_config

### ISSUE THREAD

**Issue by ghost** [graphicbeacon/dart_postgres#1]
how to connect postgres to the shelf via safe_config
https://github.com/stablekernel/safe_config

**Comment by ghost** [comment]
created the config.yaml file
```
database:
  host: localhost
  port: 5432
  databaseName: test_db
  username: test_user
  password: gfhjkm
```
and then what?
